import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { getBackend, resolveBackendConfig } from "../backend/index.js";
import { compactGitNativeLog, gitNativeFleetStats } from "../backend/git-native.js";
import { installCommands } from "./install.js";

// Phase-4 contention tripwire (docs/plans/deterministic-fleet-claiming.md § Step 6).
// Below this, linear-CAS is sufficient and NO CRDT/HRW work is justified.
export const CONTENTION_TRIPWIRE = 0.2;

// `tasks doctor` suggests compaction once the log grows past this many events.
export const COMPACTION_SUGGESTED_AT = 5000;

const CLAIMS_REF = "refs/heads/tasks-claims";

// A lefthook config (we REUSE lefthook for hook management — no hand-rolled
// merging). pre-commit lints staged TASKS.md; pre-push is the client-side
// claim-check placeholder that Phase 3's server-side required check hardens.
const LEFTHOOK_YML = `# Generated by \`tasks fleet init\`. Reuses lefthook (https://lefthook.dev)
# for hook management. Run \`lefthook install\` to activate.
pre-commit:
  commands:
    lint-tasks:
      glob: "TASKS.md"
      run: npx -y @tasks-md/lint {staged_files}
pre-push:
  commands:
    # Phase-1 ergonomic claim check. The unbypassable gate is the Phase-3
    # server-side required check (see docs/security/git-native-claims-threat-model.md).
    claim-check:
      run: npx -y @tasks-md/cli doctor --quiet
`;

// The single-writer projection workflow (spec.md § "Generated TASKS.md projection").
const PROJECTION_WORKFLOW = `# Generated by \`tasks fleet init\`. Single-writer regeneration of TASKS.md
# from the tasks-claims log. See spec.md § "Generated TASKS.md projection".
name: tasks-snapshot
on:
  push:
    branches: [tasks-claims]
  schedule:
    - cron: "*/15 * * * *"
permissions:
  contents: write
  pull-requests: write
concurrency:
  group: tasks-snapshot
  cancel-in-progress: true
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npx -y @tasks-md/cli render --backend git-native > TASKS.md
      - name: Open/update the snapshot PR
        run: |
          git config user.name "tasks-md-bot"
          git config user.email "tasks-md-bot@users.noreply.github.com"
          git checkout -B tasksmd/generated-snapshot
          git add TASKS.md
          git commit -m "chore: regenerate TASKS.md snapshot" || exit 0
          git push -f origin tasksmd/generated-snapshot
`;

// Ruleset setup is DELEGATED to existing tools (gh api / Terraform / Probot),
// never a bespoke repo-settings manager.
const RULESET_GUIDANCE = `Protect the queue with a GitHub Ruleset (pick one — all are existing tools):
  • gh api:      gh api repos/{owner}/{repo}/rulesets -f name=tasks-claims \\
                   -f target=branch --input ruleset.json   # block force-push/delete on tasks-claims + main
  • Terraform:   resource "github_repository_ruleset" "tasks_claims" { ... }
  • Probot:      add the rules to .github/settings.yml (Settings app)
See docs/security/git-native-claims-threat-model.md § "Token scope and platform differences".`;

export interface FleetInitOptions {
  backend?: "git-native" | "tasks-md";
  agent?: string;
  all?: boolean;
}

export interface FleetInitResult {
  lines: string[];
  wrote: string[];
  skipped: string[];
}

function ensureFile(path: string, content: string, result: FleetInitResult): void {
  if (existsSync(path)) {
    result.skipped.push(path);
    return;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  result.wrote.push(path);
}

/** Idempotent one-prompt fleet install. Never clobbers existing user content. */
export function runFleetInit(directory: string, options: FleetInitOptions = {}): FleetInitResult {
  const result: FleetInitResult = { lines: [], wrote: [], skipped: [] };
  const backend = options.backend ?? "git-native";

  // 1. Backend config (.tasksmd.json) — never clobber an existing one.
  const configPath = join(directory, ".tasksmd.json");
  if (existsSync(configPath)) {
    result.skipped.push(configPath);
  } else {
    writeFileSync(configPath, `${JSON.stringify({ backend }, null, 2)}\n`);
    result.wrote.push(configPath);
  }

  // 2. lefthook + projection workflow (reuse lefthook; delegate CI).
  ensureFile(join(directory, "lefthook.yml"), LEFTHOOK_YML, result);
  ensureFile(
    join(directory, ".github", "workflows", "tasks-snapshot.yml"),
    PROJECTION_WORKFLOW,
    result,
  );

  // 3. Agent commands — reuse the existing installer (auto-detect or --agent).
  try {
    const installed = installCommands(directory, join(import.meta.dirname, "..", ".."), {
      all: options.all,
      agent: options.agent,
    });
    if (installed.installed.length > 0) {
      result.lines.push(`Installed agent commands: ${installed.installed.join(", ")}.`);
    }
  } catch {
    result.lines.push("⚠ Could not install agent commands (run `tasks install` manually).");
  }

  result.lines.unshift(
    result.wrote.length > 0
      ? `Wrote: ${result.wrote.map((p) => p.replace(`${directory}/`, "")).join(", ")}.`
      : "Nothing to write — already initialized.",
  );
  if (result.skipped.length > 0) {
    result.lines.push(`Kept existing: ${result.skipped.map((p) => p.replace(`${directory}/`, "")).join(", ")}.`);
  }
  result.lines.push("");
  result.lines.push(RULESET_GUIDANCE);
  result.lines.push("");
  result.lines.push("Activate hooks with: lefthook install   (then verify: tasks doctor)");
  return result;
}

export type CheckLevel = "ok" | "warn" | "fail";

export interface DoctorCheck {
  name: string;
  level: CheckLevel;
  detail: string;
}

export interface DoctorReport {
  checks: DoctorCheck[];
  ok: boolean;
}

function gitRefExists(directory: string): boolean {
  try {
    execFileSync("git", ["show-ref", "--verify", "--quiet", CLAIMS_REF], {
      cwd: directory,
      stdio: ["pipe", "pipe", "pipe"],
    });
    return true;
  } catch {
    return false;
  }
}

/** Verify a fleet install: config, commands, hooks, claims ref, projection. */
export async function runDoctor(directory: string): Promise<DoctorReport> {
  const checks: DoctorCheck[] = [];
  const config = resolveBackendConfig(directory);
  checks.push({
    name: "backend config",
    level: "ok",
    detail: `backend = ${config.backend}${existsSync(join(directory, ".tasksmd.json")) ? "" : " (default; no .tasksmd.json)"}`,
  });

  const agentDirs = [".claude", ".agents", ".cursor", ".devin", ".gemini", ".windsurf"];
  const installed = agentDirs.filter((d) => existsSync(join(directory, d)));
  checks.push({
    name: "agent commands",
    level: installed.length > 0 ? "ok" : "warn",
    detail: installed.length > 0 ? `detected ${installed.join(", ")}` : "no agent command dirs (run `tasks install`)",
  });

  checks.push({
    name: "lefthook",
    level: existsSync(join(directory, "lefthook.yml")) ? "ok" : "warn",
    detail: existsSync(join(directory, "lefthook.yml")) ? "lefthook.yml present" : "no lefthook.yml (run `tasks fleet init`)",
  });

  if (config.backend === "git-native") {
    checks.push({
      name: "claims ref",
      level: gitRefExists(directory) ? "ok" : "warn",
      detail: gitRefExists(directory) ? `${CLAIMS_REF} present` : "no tasks-claims ref yet (created on first claim)",
    });
    checks.push({
      name: "projection workflow",
      level: existsSync(join(directory, ".github", "workflows", "tasks-snapshot.yml")) ? "ok" : "warn",
      detail: existsSync(join(directory, ".github", "workflows", "tasks-snapshot.yml"))
        ? "tasks-snapshot.yml present"
        : "no projection workflow (run `tasks fleet init`)",
    });
    // Conformance smoke: the backend must fold its log without throwing.
    try {
      await getBackend(directory).listOpen();
      checks.push({ name: "backend smoke", level: "ok", detail: "git-native log folds cleanly" });
      // Phase-2 health: stale (dead-owner) leases + log size vs compaction.
      const stats = gitNativeFleetStats(directory);
      checks.push({
        name: "stale heartbeats",
        level: stats.staleClaims > 0 ? "warn" : "ok",
        detail:
          stats.staleClaims > 0
            ? `${stats.staleClaims} claim(s) past lease expiry — reclaimable (dead owner?)`
            : "no expired leases",
      });
      checks.push({
        name: "compaction",
        level: stats.events > COMPACTION_SUGGESTED_AT ? "warn" : "ok",
        detail:
          stats.events > COMPACTION_SUGGESTED_AT
            ? `${stats.events} events — run \`tasks fleet compact\` to bound fold cost`
            : `${stats.events} events (compaction not needed)`,
      });
    } catch (error) {
      checks.push({
        name: "backend smoke",
        level: "fail",
        detail: error instanceof Error ? error.message : String(error),
      });
    }
  }

  return { checks, ok: checks.every((c) => c.level !== "fail") };
}

export function formatDoctorReport(report: DoctorReport): string {
  const icon = { ok: "✓", warn: "⚠", fail: "✗" };
  return report.checks.map((c) => `${icon[c.level]} ${c.name}: ${c.detail}`).join("\n");
}

export interface FleetStatsReport {
  lines: string[];
  contentionRatio: number;
  tripwireCrossed: boolean;
}

/** `tasks fleet stats` — contention/observability metrics for the git-native log. */
export function runFleetStats(directory: string): FleetStatsReport {
  const config = resolveBackendConfig(directory);
  if (config.backend !== "git-native") {
    return {
      lines: [`fleet stats requires the git-native backend (current: ${config.backend}).`],
      contentionRatio: 0,
      tripwireCrossed: false,
    };
  }
  const stats = gitNativeFleetStats(directory);
  const pct = (stats.contentionRatio * 100).toFixed(1);
  const crossed = stats.contentionRatio > CONTENTION_TRIPWIRE;
  const lines = [
    `Events: ${stats.events}  (created ${stats.eventsByType.created}, claimed ${stats.eventsByType.claimed}, released ${stats.eventsByType.released}, completed ${stats.eventsByType.completed}, cancelled ${stats.eventsByType.cancelled}, updated ${stats.eventsByType.updated})`,
    `Tasks: ${stats.open} open · ${stats.claimed} claimed · ${stats.done} done   Actors: ${stats.actors}`,
    `Reclaimed tasks: ${stats.reclaimedTasks}   Contention ratio: ${pct}% (tripwire ${(CONTENTION_TRIPWIRE * 100).toFixed(0)}%)`,
    crossed
      ? `⚠ contention ABOVE tripwire — Phase 4 (CRDT/HRW) is now justified; re-run the engine bake-off (docs/research/gitbug-reuse-spike.md).`
      : `✓ contention below tripwire — linear-CAS remains sufficient; no Phase 4 work is justified.`,
  ];
  return { lines, contentionRatio: stats.contentionRatio, tripwireCrossed: crossed };
}

/** `tasks fleet compact` — rewrite the local log to a fold-equivalent minimum. */
export function runFleetCompact(directory: string): string[] {
  const config = resolveBackendConfig(directory);
  if (config.backend !== "git-native") {
    return [`fleet compact requires the git-native backend (current: ${config.backend}).`];
  }
  const result = compactGitNativeLog(directory);
  return [
    `Compacted the tasks-claims log: ${result.before} → ${result.after} events (open-task state preserved).`,
    "This rewrote local history and did NOT push. Force-push it as a single-writer maintenance step, or let the projection job own the snapshot.",
  ];
}
