import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { getBackend, resolveBackendConfig } from "../backend/index.js";
import { compactGitNativeLog, gitNativeFleetStats } from "../backend/git-native.js";
import { installCommands } from "./install.js";

// Phase-4 contention tripwire (docs/plans/deterministic-fleet-claiming.md § Step 6).
// Below this, linear-CAS is sufficient and NO CRDT/HRW work is justified.
export const CONTENTION_TRIPWIRE = 0.2;

// `tasks doctor` suggests compaction once the log grows past this many events.
export const COMPACTION_SUGGESTED_AT = 5000;

const CLAIMS_REF = "refs/heads/tasks-claims";

// A lefthook config (we REUSE lefthook for hook management — no hand-rolled
// merging). pre-commit lints staged TASKS.md; pre-push is the client-side
// claim-check placeholder that Phase 3's server-side required check hardens.
const LEFTHOOK_YML = `# Generated by \`tasks fleet init\`. Reuses lefthook (https://lefthook.dev)
# for hook management. Run \`lefthook install\` to activate.
pre-commit:
  commands:
    lint-tasks:
      glob: "TASKS.md"
      run: npx -y @tasks-md/lint {staged_files}
pre-push:
  commands:
    # Phase-1 ergonomic claim check. The unbypassable gate is the Phase-3
    # server-side required check (see docs/security/git-native-claims-threat-model.md).
    claim-check:
      run: npx -y @tasks-md/cli doctor --quiet
`;

// The single-writer projection workflow (spec.md § "Generated TASKS.md projection").
const PROJECTION_WORKFLOW = `# Generated by \`tasks fleet init\`. Single-writer regeneration of TASKS.md
# from the tasks-claims log. See spec.md § "Generated TASKS.md projection".
name: tasks-snapshot
on:
  # The tasks-claims branch is an orphan log with no \`.github/workflows\`, so a
  # \`push:\` trigger there can never fire (GitHub looks for the workflow on the
  # pushed branch). Near-real-time refresh comes from a repository_dispatch the
  # git-native backend fires after a claims push (opt-in via \`.tasksmd.json\`
  # \`"autoRefresh": true\`); the schedule + on-demand are the fallbacks.
  repository_dispatch:
    types: [tasks-claims-updated]
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"
permissions:
  contents: write
  pull-requests: write
concurrency:
  group: tasks-snapshot
  cancel-in-progress: true
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      # Render to a temp file and only swap on success, so a transient failure
      # (or a CLI version that predates the git-native backend) skips the cycle
      # gracefully instead of failing the run or truncating TASKS.md.
      - run: |
          if npx -y @tasks-md/cli render --backend git-native > TASKS.md.next; then
            mv TASKS.md.next TASKS.md
          else
            echo "projection skipped: tasks render unavailable"
            rm -f TASKS.md.next
            exit 0
          fi
      - name: Open/update the snapshot PR
        run: |
          git config user.name "tasks-md-bot"
          git config user.email "tasks-md-bot@users.noreply.github.com"
          git checkout -B tasksmd/generated-snapshot
          git add TASKS.md
          git commit -m "chore: regenerate TASKS.md snapshot" || exit 0
          git push -f origin tasksmd/generated-snapshot
`;

// Phase-3 path-scoped required check (spec.md § Claim lifecycle / Security model).
// Reuses the CLI's `check-push` so the path rule never drifts from the backend.
const CLAIM_CHECK_WORKFLOW = `# Generated by \`tasks fleet init\`. Path-scoped claim gate.
#
# ADVISORY BY DEFAULT: a code change without a live task claim WARNS but does
# not block, so this never red-X's a bootstrap PR, a doc PR, or a human
# contribution. To make it a HARD gate (the threat model's "advisory → hard"
# step): set the repo variable \`TASKS_CLAIM_ENFORCE=1\`
# (\`gh variable set TASKS_CLAIM_ENFORCE --body 1\`) AND mark this check
# required on a branch ruleset that also blocks force-push/delete of
# \`tasks-claims\`. See docs/security/git-native-claims-threat-model.md.
#
# Uses pull_request (NOT pull_request_target) so untrusted forks can't read secrets.
name: tasks-claim-check
on:
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  claim-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - name: Path-scoped claim check
        env:
          ENFORCE: \${{ vars.TASKS_CLAIM_ENFORCE }}
          # Resolve the TRUSTED published cli from public npm. This runs on
          # pull_request (untrusted PR head), so we must NOT build the PR's own
          # cli (a malicious PR could rewrite check-push to always pass and
          # bypass its own claim check). The pin also dodges registry mirror lag
          # that otherwise leaves a fresh release uninstallable -> vacuous pass.
          npm_config_registry: https://registry.npmjs.org
        run: |
          base="origin/\${{ github.base_ref }}"
          paths=$(git diff --name-only "$base...HEAD")
          [ -z "$paths" ] && { echo "no changes"; exit 0; }
          # The pull_request HEAD is the auto-merge commit (no trailers), so scan
          # the PR's own commits (base..HEAD) for the newest Task / Task-Claim.
          # git's own trailer parser (same engine as git interpret-trailers).
          task=$(git log "$base..HEAD" --format='%(trailers:key=Task,valueonly)' | grep -m1 . || true)
          claim=$(git log "$base..HEAD" --format='%(trailers:key=Task-Claim,valueonly)' | grep -m1 . || true)
          git fetch origin '+refs/heads/tasks-claims:refs/heads/tasks-claims' || true
          if npx -y @tasks-md/cli check-push --task "$task" --claim "$claim" $paths; then
            exit 0
          fi
          # check-push rejected (code change without a valid live claim).
          if [ -n "$ENFORCE" ] && [ "$ENFORCE" != "0" ] && [ "$ENFORCE" != "false" ]; then
            echo "::error::code change without a live task claim (TASKS_CLAIM_ENFORCE is on)"
            exit 1
          fi
          echo "::warning::code change without a live task claim — advisory only. Set repo variable TASKS_CLAIM_ENFORCE=1 (+ required ruleset check) to enforce."
          exit 0
`;

// Ruleset setup is DELEGATED to existing tools (gh api / Terraform / Probot),
// never a bespoke repo-settings manager.
const RULESET_GUIDANCE = `Protect the queue with a GitHub Ruleset (pick one — all are existing tools):
  • gh api:      gh api repos/{owner}/{repo}/rulesets -f name=tasks-claims \\
                   -f target=branch --input ruleset.json   # block force-push/delete on tasks-claims + main
  • Terraform:   resource "github_repository_ruleset" "tasks_claims" { ... }
  • Probot:      add the rules to .github/settings.yml (Settings app)
See docs/security/git-native-claims-threat-model.md § "Token scope and platform differences".`;

export interface FleetInitOptions {
  backend?: "git-native" | "tasks-md";
  agent?: string;
  all?: boolean;
}

export interface FleetInitResult {
  lines: string[];
  wrote: string[];
  skipped: string[];
}

function ensureFile(path: string, content: string, result: FleetInitResult): void {
  if (existsSync(path)) {
    result.skipped.push(path);
    return;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  result.wrote.push(path);
}

/** Idempotent one-prompt fleet install. Never clobbers existing user content. */
export function runFleetInit(directory: string, options: FleetInitOptions = {}): FleetInitResult {
  const result: FleetInitResult = { lines: [], wrote: [], skipped: [] };
  const backend = options.backend ?? "git-native";

  // 1. Backend config (.tasksmd.json) — never clobber an existing one.
  const configPath = join(directory, ".tasksmd.json");
  if (existsSync(configPath)) {
    result.skipped.push(configPath);
  } else {
    writeFileSync(configPath, `${JSON.stringify({ backend }, null, 2)}\n`);
    result.wrote.push(configPath);
  }

  // 2. lefthook + projection + claim-check workflows (reuse lefthook; delegate CI).
  ensureFile(join(directory, "lefthook.yml"), LEFTHOOK_YML, result);
  ensureFile(
    join(directory, ".github", "workflows", "tasks-snapshot.yml"),
    PROJECTION_WORKFLOW,
    result,
  );
  ensureFile(
    join(directory, ".github", "workflows", "tasks-claim-check.yml"),
    CLAIM_CHECK_WORKFLOW,
    result,
  );

  // 3. Agent commands — reuse the existing installer (auto-detect or --agent).
  try {
    const installed = installCommands(directory, join(import.meta.dirname, "..", ".."), {
      all: options.all,
      agent: options.agent,
    });
    if (installed.installed.length > 0) {
      result.lines.push(`Installed agent commands: ${installed.installed.join(", ")}.`);
    }
  } catch {
    result.lines.push("⚠ Could not install agent commands (run `tasks install` manually).");
  }

  result.lines.unshift(
    result.wrote.length > 0
      ? `Wrote: ${result.wrote.map((p) => p.replace(`${directory}/`, "")).join(", ")}.`
      : "Nothing to write — already initialized.",
  );
  if (result.skipped.length > 0) {
    result.lines.push(`Kept existing: ${result.skipped.map((p) => p.replace(`${directory}/`, "")).join(", ")}.`);
  }
  result.lines.push("");
  result.lines.push(RULESET_GUIDANCE);
  result.lines.push("");
  result.lines.push("Activate hooks with: lefthook install   (then verify: tasks doctor)");
  return result;
}

export type CheckLevel = "ok" | "warn" | "fail";

export interface DoctorCheck {
  name: string;
  level: CheckLevel;
  detail: string;
}

export interface DoctorReport {
  checks: DoctorCheck[];
  ok: boolean;
}

function gitRefExists(directory: string): boolean {
  try {
    execFileSync("git", ["show-ref", "--verify", "--quiet", CLAIMS_REF], {
      cwd: directory,
      stdio: ["pipe", "pipe", "pipe"],
    });
    return true;
  } catch {
    return false;
  }
}

/** Verify a fleet install: config, commands, hooks, claims ref, projection. */
export async function runDoctor(directory: string): Promise<DoctorReport> {
  const checks: DoctorCheck[] = [];
  const config = resolveBackendConfig(directory);
  checks.push({
    name: "backend config",
    level: "ok",
    detail: `backend = ${config.backend}${existsSync(join(directory, ".tasksmd.json")) ? "" : " (default; no .tasksmd.json)"}`,
  });

  const agentDirs = [".claude", ".agents", ".cursor", ".devin", ".gemini", ".windsurf"];
  const installed = agentDirs.filter((d) => existsSync(join(directory, d)));
  checks.push({
    name: "agent commands",
    level: installed.length > 0 ? "ok" : "warn",
    detail: installed.length > 0 ? `detected ${installed.join(", ")}` : "no agent command dirs (run `tasks install`)",
  });

  checks.push({
    name: "lefthook",
    level: existsSync(join(directory, "lefthook.yml")) ? "ok" : "warn",
    detail: existsSync(join(directory, "lefthook.yml")) ? "lefthook.yml present" : "no lefthook.yml (run `tasks fleet init`)",
  });

  if (config.backend === "git-native") {
    checks.push({
      name: "claims ref",
      level: gitRefExists(directory) ? "ok" : "warn",
      detail: gitRefExists(directory) ? `${CLAIMS_REF} present` : "no tasks-claims ref yet (created on first claim)",
    });
    checks.push({
      name: "projection workflow",
      level: existsSync(join(directory, ".github", "workflows", "tasks-snapshot.yml")) ? "ok" : "warn",
      detail: existsSync(join(directory, ".github", "workflows", "tasks-snapshot.yml"))
        ? "tasks-snapshot.yml present"
        : "no projection workflow (run `tasks fleet init`)",
    });
    // Conformance smoke: the backend must fold its log without throwing.
    try {
      await getBackend(directory).listOpen();
      checks.push({ name: "backend smoke", level: "ok", detail: "git-native log folds cleanly" });
      // Phase-2 health: stale (dead-owner) leases + log size vs compaction.
      const stats = gitNativeFleetStats(directory);
      checks.push({
        name: "stale heartbeats",
        level: stats.staleClaims > 0 ? "warn" : "ok",
        detail:
          stats.staleClaims > 0
            ? `${stats.staleClaims} claim(s) past lease expiry — reclaimable (dead owner?)`
            : "no expired leases",
      });
      checks.push({
        name: "compaction",
        level: stats.events > COMPACTION_SUGGESTED_AT ? "warn" : "ok",
        detail:
          stats.events > COMPACTION_SUGGESTED_AT
            ? `${stats.events} events — run \`tasks fleet compact\` to bound fold cost`
            : `${stats.events} events (compaction not needed)`,
      });
      // Phase-3 enforcement level: absent → advisory (client hook) → hard
      // (server-side required check). The required-check workflow being present
      // is advisory until it is also a *required* status check on the branch
      // ruleset — which the doctor can't see from the clone, so it reports the
      // ceiling and points at the ruleset step.
      const hasClaimCheck = existsSync(
        join(directory, ".github", "workflows", "tasks-claim-check.yml"),
      );
      const hasClientHook = existsSync(join(directory, "lefthook.yml"));
      checks.push({
        name: "enforcement",
        level: hasClaimCheck || hasClientHook ? "ok" : "warn",
        detail: hasClaimCheck
          ? "advisory→hard: claim-check workflow present (advisory by default — warns, doesn't block). For hard enforcement set repo var `TASKS_CLAIM_ENFORCE=1`, make the check REQUIRED, and add the ruleset (see `tasks fleet init` output)"
          : hasClientHook
            ? "advisory: client pre-push hook only (bypassable) — add the claim-check workflow with `tasks fleet init`"
            : "absent: no claim-check workflow or client hook (run `tasks fleet init`)",
      });
    } catch (error) {
      checks.push({
        name: "backend smoke",
        level: "fail",
        detail: error instanceof Error ? error.message : String(error),
      });
    }
  }

  return { checks, ok: checks.every((c) => c.level !== "fail") };
}

export function formatDoctorReport(report: DoctorReport): string {
  const icon = { ok: "✓", warn: "⚠", fail: "✗" };
  return report.checks.map((c) => `${icon[c.level]} ${c.name}: ${c.detail}`).join("\n");
}

export interface FleetStatsReport {
  lines: string[];
  contentionRatio: number;
  tripwireCrossed: boolean;
}

/** `tasks fleet stats` — contention/observability metrics for the git-native log. */
export function runFleetStats(directory: string): FleetStatsReport {
  const config = resolveBackendConfig(directory);
  if (config.backend !== "git-native") {
    return {
      lines: [`fleet stats requires the git-native backend (current: ${config.backend}).`],
      contentionRatio: 0,
      tripwireCrossed: false,
    };
  }
  const stats = gitNativeFleetStats(directory);
  const pct = (stats.contentionRatio * 100).toFixed(1);
  const crossed = stats.contentionRatio > CONTENTION_TRIPWIRE;
  const lines = [
    `Events: ${stats.events}  (created ${stats.eventsByType.created}, claimed ${stats.eventsByType.claimed}, released ${stats.eventsByType.released}, completed ${stats.eventsByType.completed}, cancelled ${stats.eventsByType.cancelled}, updated ${stats.eventsByType.updated})`,
    `Tasks: ${stats.open} open · ${stats.claimed} claimed · ${stats.done} done   Actors: ${stats.actors}`,
    `Reclaimed tasks: ${stats.reclaimedTasks}   Contention ratio: ${pct}% (tripwire ${(CONTENTION_TRIPWIRE * 100).toFixed(0)}%)`,
    crossed
      ? `⚠ contention ABOVE tripwire — Phase 4 (CRDT/HRW) is now justified; re-run the engine bake-off (docs/research/gitbug-reuse-spike.md).`
      : `✓ contention below tripwire — linear-CAS remains sufficient; no Phase 4 work is justified.`,
  ];
  return { lines, contentionRatio: stats.contentionRatio, tripwireCrossed: crossed };
}

/** `tasks fleet compact` — rewrite the local log to a fold-equivalent minimum. */
export function runFleetCompact(directory: string): string[] {
  const config = resolveBackendConfig(directory);
  if (config.backend !== "git-native") {
    return [`fleet compact requires the git-native backend (current: ${config.backend}).`];
  }
  const result = compactGitNativeLog(directory);
  return [
    `Compacted the tasks-claims log: ${result.before} → ${result.after} events (open-task state preserved).`,
    "This rewrote local history and did NOT push. Force-push it as a single-writer maintenance step, or let the projection job own the snapshot.",
  ];
}
